"""empty message

Revision ID: 052a5fe5b498
Revises: 2807edd385a2
Create Date: 2022-03-31 04:29:20.458741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052a5fe5b498'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=250), nullable=False),
    sa.Column('stage', sa.Enum('notdone', 'inprogress', 'done', name='TodoType'), nullable=False),
    sa.Column('duedate', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('todos')
    # ### end Alembic commands ###
